# 데이터베이스 연결
spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:tcp://localhost/~/test
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # 구글 로그인
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 385042863793-qlrrdmlcs44js199mq6eivmtd01i24kg.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

# jwt 개인키
security:
  jwt:
    secretKey: SpringBoot3Security6TESTSpringBoot3Security6TESTSpringBoot3Security6TESTSpringBoot3Security6TESTSpringBoot3Security6TESTSpringBoot3Security6TESTSpringBoot3Security6TESTSpringBoot3Security6TESTSpringBoot3Security6TESTSpringBoot3Security6TESTSpringBoot3Security6TESTSpringBoot3Security6TESTSpringBoot3Security6TESTSpringBoot3Security6TESTSpringBoot3Security6TESTSpringBoot3Security6TESTSpringBoot3Security6TESTSpringBoot3Security6TESTSpringBoot3Security6TESTSpringBoot3Security6TEST

# 이메일 인증 관련
mail:
  smtp:
    auth: true
    port: 465
    socketFactory:
      class: javax.net.ssl.SSLSocketFactory
      fallback: false
      port: 465
    starttls:
      required: true
      enable: true


admin:
  id: victoryddh
  password: ccppzijdnraxqzhb