server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

security:
  jwt:
    secretKey : springboot3springsecurity6TESTspringboot3springsecurity6TESTspringboot3springsecurity6TESTspringboot3springsecurity6TESTspringboot3springsecurity6TESTspringboot3springsecurity6TESTspringboot3springsecurity6TESTspringboot3springsecurity6TESTspringboot3springsecurity6TESTspringboot3springsecurity6TESTspringboot3springsecurity6TESTspringboot3springsecurity6TESTspringboot3springsecurity6TEST