spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:tcp://localhost/~/test
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


security:
  jwt:
    secretKey: SpringBoot3Security6TESTSpringBoot3Security6TESTSpringBoot3Security6TESTSpringBoot3Security6TESTSpringBoot3Security6TESTSpringBoot3Security6TESTSpringBoot3Security6TESTSpringBoot3Security6TESTSpringBoot3Security6TESTSpringBoot3Security6TESTSpringBoot3Security6TESTSpringBoot3Security6TESTSpringBoot3Security6TESTSpringBoot3Security6TESTSpringBoot3Security6TESTSpringBoot3Security6TESTSpringBoot3Security6TESTSpringBoot3Security6TESTSpringBoot3Security6TESTSpringBoot3Security6TEST